feat: change password
canonical/gocert pull request #45
Opened 2024-07-24 10:05 UTC by kayra1

# Description

This change lets users change password in gocert.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-24 12:56 UTC, gruyaume requested changes

2024-07-24 13:15 UTC, kayra1 commented on ui/src/app/nav.tsx
> -                                <ul className="p-side-navigation__list" style={{ bottom: 0, position: "absolute", width: "100%" }}>
yes, because it seems like the dropdown menu can't drop up. I think I also like it below the tabs, but wanted to see what you think.

2024-07-24 13:20 UTC, gruyaume commented on ui/src/app/nav.tsx
> -                                <ul className="p-side-navigation__list" style={{ bottom: 0, position: "absolute", width: "100%" }}>
The menu could pop out just like the menu next to each certificate line

2024-07-24 13:40 UTC, kayra1 commented on ui/src/app/nav.tsx
> -                                <ul className="p-side-navigation__list" style={{ bottom: 0, position: "absolute", width: "100%" }}>
it does, that's the dropdown menu provided by vanilla that we use here, but it only pops out below the user tab, creating a scroll wheel in the sidebar. Even the vanilla examples do that in the docs page.

if you add the `style={{ bottom: 0, position: "absolute", width: "100%" }}` back to the line, you can see how it looks

2024-07-24 16:44 UTC, gruyaume commented on ui/src/app/nav.tsx
> -                                <ul className="p-side-navigation__list" style={{ bottom: 0, position: "absolute", width: "100%" }}>
If the menu options are always expanded, can we make it stick to the bottom ? I'm sure there's something we can do.

Ex. in MAAS

2024-07-24 17:01 UTC, kayra1 commented on ui/src/app/nav.tsx
> -                                <ul className="p-side-navigation__list" style={{ bottom: 0, position: "absolute", width: "100%" }}>
they are not, but they could be. I like the MAAS look

2024-07-25 12:15 UTC, kayra1 commented on ui/src/app/nav.tsx
> -                                <ul className="p-side-navigation__list" style={{ bottom: 0, position: "absolute", width: "100%" }}>
I added some styling so the dropdown menu drops above now. It's a bit of a hack but it seems to work and look fine

2024-07-25 14:13 UTC, gruyaume approved these changes

2024-07-26 08:35 UTC, merged